import { Geist, Geist_Mono } from "next/font/google";
import { Baloo_2 } from "next/font/google"; // ✅ import Baloo 2
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const baloo = Baloo_2({
  variable: "--font-baloo",
  subsets: ["latin"],
  weight: ["400", "700"], // available weights
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* add baloo.variable here so CSS can use it */}
      <body className={`${geistSans.variable} ${geistMono.variable} ${baloo.variable}`}>
        {children}
      </body>
    </html>
  );
}
